services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/juke/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/juke/homepage/images:/app/public/images
