services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.11.6
    ports:
      # The HTTP port
      - "80:80" # web
      - "443:443" # websecure
      # The Web UI (enabled by --api.insecure=true)
      - "8081:8080"
    volumes:
      # Config file
      - /etc/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # For TLS certs not to be re-generated every time...
      - /etc/traefik/certs/acme.json:/acme.json
      # Mount SSL certificates
      - /etc/traefik/certs/fullchain.pem:/certs/fullchain.pem
      - /etc/traefik/certs/private.key.pem:/certs/private.key.pem
    networks:
      - nginx

networks:
  nginx:
    external: true
