services:
  nginx:
    container_name: nginx
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`jukelyn.com`)"
      - "traefik.http.routers.nginx.entrypoints=web,websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=staging"
    volumes:
      - /home/juke/sites/mysite/public:/usr/share/nginx/html
#      - /home/juke/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - nginx

networks:
  nginx:
    external: true

