---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 9443

# my-docker:
#   socket: /var/run/docker.sock
